In [1]:
import torch
from torch import nn

/Users/manasnanivadekar/Projects/ml-papers/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
net = nn.Sequential(nn.LazyLinear(8),
                    nn.ReLU(),
                    nn.LazyLinear(1))

X = torch.rand(size=(2, 4))
net(X).shape

torch.Size([2, 1])

In [6]:
net[2].state_dict()

OrderedDict([('weight',
              tensor([[ 0.1079,  0.3461,  0.0857,  0.2174,  0.0198, -0.1520,  0.2102,  0.0443]])),
             ('bias', tensor([0.2757]))])

In [7]:
type(net[2].bias), net[2].bias.data

(torch.nn.parameter.Parameter, tensor([0.2757]))

In [8]:
[(name, param.shape) for name, param in net.named_parameters()]

[('0.weight', torch.Size([8, 4])),
 ('0.bias', torch.Size([8])),
 ('2.weight', torch.Size([1, 8])),
 ('2.bias', torch.Size([1]))]

In [ ]:
shared = nn.LazyLinear(8)
net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(),
                    shared, nn.ReLU(),
                    shared, nn.ReLU(),
                    nn.LazyLinear(1))

net(X)

print(net[2].weight.data[0] == net[4].weight.data[0]) # type: ignore
net[2].weight.data[0, 0] = 100

print(net[2].weight.data[0] == net[4].weight.data[0]) # pyright: ignore[reportIndexIssue]

tensor([True, True, True, True, True, True, True, True])
tensor([True, True, True, True, True, True, True, True])
